/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.Controller;
import Modelo.Conexion;
import java.awt.Color;
import static java.awt.SystemColor.control;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author andre
 */
public class GestionOdontologos1 extends javax.swing.JPanel {
Controller control;
public static String Cedula_new = "";
    /**
     * Creates new form GestionOdontologos1
     */
    public GestionOdontologos1(String ci) {
        initComponents();
        String cu= ci;
        control = new Controller();
        try{
         Connection cn = Conexion.conectarBD();
         PreparedStatement pst = cn.prepareStatement("select * from odontologos where Cedula = '" + ci + "'");

         ResultSet rs = pst.executeQuery();
         
         if(rs.next()){
             
             
             Nombre.setText(rs.getString("Nombre"));
             Cedula.setText(rs.getString("Cedula"));
             Direccion.setText(rs.getString("Direccion"));
             TextCargo.setText(rs.getString("Cargo"));
             TextEspe.setText(rs.getString("Especialidad"));
             TextTelefono.setText(rs.getString("Telefono"));
             
             Usuario.setText(rs.getString("Usuario"));
             Correo.setText(rs.getString("Correo"));
             Clave.setText(rs.getString("Clave"));
             TextObservaciones.setText(rs.getString("Observaciones"));
        }
         
        cn.close();
     }catch(Exception e){
         System.out.println("Error en cargar odontólogo" + e);
        // JOptionPane.showMessageDialog(null), "ESCRIBALE A ANDI");
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelRound15 = new Modelo.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        panelRound3 = new Modelo.PanelRound();
        panelRound4 = new Modelo.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextTelefono = new javax.swing.JTextField();
        ListTel = new javax.swing.JComboBox<>();
        TextObservaciones = new javax.swing.JTextField();
        TextCargo = new javax.swing.JTextField();
        TextEspe = new javax.swing.JTextField();
        BEliminar = new javax.swing.JButton();
        BModificar = new javax.swing.JButton();
        Error_Nombre = new javax.swing.JTextField();
        Error_Cedula = new javax.swing.JTextField();
        Error_Direccion = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Usuario = new javax.swing.JTextField();
        Clave = new javax.swing.JTextField();
        Error_Correo = new javax.swing.JTextField();
        Error_Usuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panelRound1 = new Modelo.PanelRound();
        jLabel12 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 249, 255));

        panelRound15.setBackground(new java.awt.Color(5, 179, 242));
        panelRound15.setRoundBottomLeft(50);
        panelRound15.setRoundBottomRight(50);
        panelRound15.setRoundTopLeft(50);
        panelRound15.setRoundTopRight(50);

        panelRound3.setBackground(new java.awt.Color(5, 179, 242));
        panelRound3.setRoundBottomLeft(50);
        panelRound3.setRoundBottomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(50);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound4.setBackground(new java.awt.Color(88, 234, 253));
        panelRound4.setRoundBottomLeft(50);
        panelRound4.setRoundBottomRight(50);
        panelRound4.setRoundTopLeft(50);
        panelRound4.setRoundTopRight(50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos del Odontólogo");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound3.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 900, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Dirección");
        panelRound3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, 20));

        TextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefonoActionPerformed(evt);
            }
        });
        TextTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextTelefonoKeyTyped(evt);
            }
        });
        panelRound3.add(TextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, 31));

        ListTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "0212", "0412", "0414", "0424", "0416", "0426" }));
        ListTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListTelActionPerformed(evt);
            }
        });
        panelRound3.add(ListTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, 30));
        panelRound3.add(TextObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 260, 80));
        panelRound3.add(TextCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 170, 30));

        TextEspe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEspeActionPerformed(evt);
            }
        });
        panelRound3.add(TextEspe, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 170, 30));

        BEliminar.setBackground(new java.awt.Color(153, 0, 0));
        BEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BEliminar.setText("Eliminar");
        BEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BEliminarMouseExited(evt);
            }
        });
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });
        panelRound3.add(BEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 170, 40));

        BModificar.setBackground(new java.awt.Color(0, 0, 102));
        BModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BModificar.setForeground(new java.awt.Color(255, 255, 255));
        BModificar.setText("Modificar");
        BModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BModificarMouseExited(evt);
            }
        });
        BModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificarActionPerformed(evt);
            }
        });
        panelRound3.add(BModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 160, 40));

        Error_Nombre.setEditable(false);
        Error_Nombre.setBackground(new java.awt.Color(0,0,0,1));
        Error_Nombre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Nombre.setForeground(new java.awt.Color(255, 0, 0));
        Error_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Nombre.setBorder(null);
        panelRound3.add(Error_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 240, 20));

        Error_Cedula.setEditable(false);
        Error_Cedula.setBackground(new java.awt.Color(0,0,0,1));
        Error_Cedula.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Cedula.setForeground(new java.awt.Color(255, 0, 0));
        Error_Cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Cedula.setBorder(null);
        Error_Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_CedulaActionPerformed(evt);
            }
        });
        panelRound3.add(Error_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 250, 20));

        Error_Direccion.setEditable(false);
        Error_Direccion.setBackground(new java.awt.Color(0,0,0,1));
        Error_Direccion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Direccion.setForeground(new java.awt.Color(255, 0, 0));
        Error_Direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Direccion.setBorder(null);
        Error_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_DireccionActionPerformed(evt);
            }
        });
        panelRound3.add(Error_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 260, 20));

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });
        panelRound3.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 30));

        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });
        Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CedulaKeyTyped(evt);
            }
        });
        panelRound3.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 218, 30));

        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionKeyTyped(evt);
            }
        });
        panelRound3.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 230, 30));

        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CorreoKeyTyped(evt);
            }
        });
        panelRound3.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 250, 30));

        Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioKeyTyped(evt);
            }
        });
        panelRound3.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 190, 30));

        Clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ClaveKeyTyped(evt);
            }
        });
        panelRound3.add(Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 213, 30));

        Error_Correo.setEditable(false);
        Error_Correo.setBackground(new java.awt.Color(0,0,0,1));
        Error_Correo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Correo.setForeground(new java.awt.Color(255, 0, 0));
        Error_Correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Correo.setBorder(null);
        Error_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_CorreoActionPerformed(evt);
            }
        });
        panelRound3.add(Error_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 280, 20));

        Error_Usuario.setEditable(false);
        Error_Usuario.setBackground(new java.awt.Color(0,0,0,1));
        Error_Usuario.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Usuario.setForeground(new java.awt.Color(255, 0, 0));
        Error_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Usuario.setBorder(null);
        panelRound3.add(Error_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 260, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Contraseña");
        panelRound3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Cédula");
        panelRound3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Nombre Completo");
        panelRound3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Teléfono");
        panelRound3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Cargo");
        panelRound3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Especialidad");
        panelRound3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Observaciones");
        panelRound3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Usuario");
        panelRound3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Correo electrónico");
        panelRound3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 20));

        javax.swing.GroupLayout panelRound15Layout = new javax.swing.GroupLayout(panelRound15);
        panelRound15.setLayout(panelRound15Layout);
        panelRound15Layout.setHorizontalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound15Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 771, Short.MAX_VALUE))
            .addGroup(panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound15Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(21, 21, 21)))
        );
        panelRound15Layout.setVerticalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound15Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelRound1.setBackground(new java.awt.Color(5, 179, 242));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GESTIÓN DE ODONTÓLOGOS");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel12)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(126, 126, 126))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound15, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefonoActionPerformed

    private void TextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextTelefonoKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras (solo numeros)","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
        if (TextTelefono.getText().trim().length() >=7) {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA el telefono debe tener 7 digitos","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_TextTelefonoKeyTyped

    private void ListTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListTelActionPerformed

    private void TextEspeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEspeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEspeActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed

        String ci= Cedula.getText();
        String name_up= Nombre.getText();
        boolean a=false;
        if(  JOptionPane.showConfirmDialog(null, "¿Seguro de que desea eliminar al odontólogo "+name_up+" C.I "+ci+" ?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            a=true;
            try {
                Connection cn = Conexion.conectarBD();
                String sql = "DELETE FROM odontologos WHERE Cedula = '" + ci + "'"; // le indico a quien debe borra pasandole la cedula
                PreparedStatement ps = cn.prepareStatement(sql);
                ps.executeUpdate();
                cn.close();
                JOptionPane.showMessageDialog(null,"¡El odontólogo fue eliminado con éxito!");
                Limpiar();
                GestionOdontologos destino = new GestionOdontologos();
                control.ConectarPanel(jPanel2, destino,  960, 639, 0, 0); 

        } catch (Exception e) {
            System.err.println("Error al eliminar al odontólogo de la tabla." + e);
            JOptionPane.showMessageDialog(null, "Debe estar activa la base de datos, ¡Contacte al administrador!");}
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificarActionPerformed
        int permisos, estatus, validacion =0;
        String nombre, cargo, mail, telefono, ci, direccion, usuario, especialidad, clave, observaciones;

        cargo = TextCargo.getText().trim();
        mail = Correo.getText().trim();
        nombre = Nombre.getText().trim();
        ci = Cedula.getText().trim();
        direccion = Direccion.getText().trim();
        telefono = TextTelefono.getText().trim();
        usuario = Usuario.getText().trim();
        especialidad = TextEspe.getText().trim();
        clave = Clave.getText().trim();
        observaciones = TextObservaciones.getText().trim();

        if(mail.equals("")){
            Correo.setBackground(Color.red);
            validacion ++;
        }
        if(nombre.equals("")){
            Nombre.setBackground(Color.red);
            validacion ++;
        }
        if(ci.equals("")){
            Cedula.setBackground(Color.red);
            validacion ++;
        }
        if(direccion.equals("")){
            Direccion.setBackground(Color.red);
            validacion ++;
        }
        if(telefono.equals("")){
            TextTelefono.setBackground(Color.red);
            validacion ++;
        }
        if(usuario.equals("")){
            Usuario.setBackground(Color.red);
            validacion ++;
        }
        if(especialidad.equals("")){
            TextEspe.setBackground(Color.red);
            validacion ++;
        }
        if(clave.equals("")){
            Clave.setBackground(Color.red);
            validacion ++;
        }

        if(validacion==0){

            try {
                Connection cn2 = Conexion.conectarBD();
                String Ssql = "UPDATE odontologos SET Nombre= ?, Direccion= ?, Telefono= ?, Correo= ?, Usuario= ?, Clave= ?, Especialidad= ?, Observaciones= ? " + "WHERE Cedula = '" + ci + "'";
                PreparedStatement prest = cn2.prepareStatement(Ssql);

                prest.setString(1, nombre);
                prest.setString(2, direccion);
                prest.setString(3, telefono);
                prest.setString(4, mail);
                prest.setString(5, usuario);
                prest.setString(6, clave);
                prest.setString(7, especialidad);
                prest.setString(8, observaciones);

                prest.executeUpdate();

                cn2.close();
                JOptionPane.showMessageDialog(null, "Modificacion correcta");

            } catch (Exception e) {
                System.err.println("Error al Actualizar "+ e);
            }

        } else{
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }
    }//GEN-LAST:event_BModificarActionPerformed

    private void Error_CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_CedulaActionPerformed

    private void Error_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_DireccionActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed

    }//GEN-LAST:event_NombreActionPerformed

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)){

            Error_Nombre.setText("No se aceptan caracteres especiales ni números");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales ni numeros","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);

            evt.consume();
        }
    }//GEN-LAST:event_NombreKeyTyped

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Cedula.setText("No se aceptan caracteres especiales ni letras");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
        if (Cedula.getText().trim().length() > 7) {
            Error_Cedula.setText("La cédula debe tener 6-8 dígitos");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA la cedula debe tener 6-8 digitos","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_CedulaKeyTyped

    private void DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;
        boolean numeros= (key >= 48 && key <= 57);
        if (!(minusculas || mayusculas || espacio || numeros)){

            Error_Direccion.setText("No se aceptan caracteres especiales.");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);

            evt.consume();
        }
    }//GEN-LAST:event_DireccionKeyTyped

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoKeyTyped

    private void UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioKeyTyped

    private void ClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClaveKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ClaveKeyTyped

    private void Error_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_CorreoActionPerformed

    private void BModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BModificarMouseEntered
        BModificar.setBackground(new Color(4,119,255));
    }//GEN-LAST:event_BModificarMouseEntered

    private void BModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BModificarMouseExited
        BModificar.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_BModificarMouseExited

    private void BEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEliminarMouseEntered
        BEliminar.setBackground(new Color(249,16,0));
    }//GEN-LAST:event_BEliminarMouseEntered

    private void BEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEliminarMouseExited
        BEliminar.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_BEliminarMouseExited

    
    public void Limpiar(){
        Nombre.setText("");
        Cedula.setText("");
        TextTelefono.setText("");
        Direccion.setText("");
        Usuario.setText("");
        Clave.setText("");
        TextObservaciones.setText("");
        Correo.setText("");
        TextEspe.setText("");
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BModificar;
    private javax.swing.JTextField Cedula;
    private javax.swing.JTextField Clave;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Error_Cedula;
    private javax.swing.JTextField Error_Correo;
    private javax.swing.JTextField Error_Direccion;
    private javax.swing.JTextField Error_Nombre;
    private javax.swing.JTextField Error_Usuario;
    private javax.swing.JComboBox<String> ListTel;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField TextCargo;
    private javax.swing.JTextField TextEspe;
    private javax.swing.JTextField TextObservaciones;
    private javax.swing.JTextField TextTelefono;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private Modelo.PanelRound panelRound1;
    private Modelo.PanelRound panelRound15;
    private Modelo.PanelRound panelRound3;
    private Modelo.PanelRound panelRound4;
    // End of variables declaration//GEN-END:variables
}
