/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.Controller;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author andre
 */
public class GestionPerfil extends javax.swing.JPanel {  
    
    //Variables para que se llene la tabla cuando seleccione
        
        public static String nombre_llenar = "";
        public static String cedula_llenar = "";
        public static String direccion_llenar = "";
        public static String telefono_llenar = "";
        public static String correo_llenar = "";
        public static String cargo_llenar = "";
        public static String usuario_llenar = "";
        public static String clave_llenar = "";

 Controller control;
 String Cedu;
 String Nom;
    public GestionPerfil() {
        initComponents();
        control= new Controller(TextNombre,TextCI,TextDireccion,TextTelefono, TextCorreo,Cargo, TextUsuario, TextClave, Error_Nombre, Error_Cedula, Error_Correo, CodNum, TablaPerfiles, Error_Usuario, Error_Telefono);
        control.LlenarTablaPerfil();
    }
    public GestionPerfil(String CeduNom) {
        String Cedul[]= CeduNom.split("-");
        this.Cedu=Cedul[0];
        this.Nom=Cedul[1];
        
                
        initComponents();
        control= new Controller(TextNombre,TextCI,TextDireccion,TextTelefono, TextCorreo,Cargo, TextUsuario, TextClave, Error_Nombre, Error_Cedula, Error_Correo, CodNum, TablaPerfiles, Error_Usuario, Error_Telefono);
        control.LlenarTablaPerfil();
        
      /*  TablaPerfiles.addMouseListener(new MouseAdapter(){
        @Override
           public void mouseClicked(MouseEvent e){
                int fila_point = TablaPerfiles.rowAtPoint(e.getPoint());
                int columna_point = 1;
                
                if(fila_point > -1){
                    nombre_llenar = (String)model.getValueAt(fila_point, 0);
                    cedula_llenar = (String)model.getValueAt(fila_point, columna_point);
                    TextTelefono = (String)model.getValueAt(fila_point, 2);
                    TextDireccion = (String)model.getValueAt(fila_point, 2);
                    TextCorreo = (String)model.getValueAt(fila_point, 3);
                    Cargo = (String)model.getValueAt(fila_point, 4);
                    TextUsuario = (String)model.getValueAt(fila_point, 5);
                    TextClave = ()model.getValueAt(fila_point, 5);
                    //JOptionPane.showMessageDialog(null, "El tipo de cliente seleccionado es: "+tipocliente_update);
                    
                    
                    
                    //Aqui se llenan los campos
                    
                    
                }
            }
        })*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        BModificarP5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Modelo.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        panelRound2 = new Modelo.PanelRound();
        TextCI = new javax.swing.JTextField();
        TextCorreo = new javax.swing.JTextField();
        TextDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextUsuario = new javax.swing.JTextField();
        TextClave = new javax.swing.JTextField();
        TextNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPerfiles = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelRound4 = new Modelo.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        Modificar = new rsbuttom.RSButtonMetro();
        Eliminar = new rsbuttom.RSButtonMetro();
        Consultar = new rsbuttom.RSButtonMetro();
        Cargo = new javax.swing.JComboBox<>();
        Error_Nombre = new javax.swing.JTextField();
        Error_Cedula = new javax.swing.JTextField();
        Error_Correo = new javax.swing.JTextField();
        CodNum = new javax.swing.JComboBox<>();
        TextTelefono = new javax.swing.JTextField();
        Error_Usuario = new javax.swing.JTextField();
        Error_Telefono = new javax.swing.JTextField();

        Principal.setBackground(new java.awt.Color(255, 255, 255));
        Principal.setLayout(new java.awt.BorderLayout());

        BModificarP5.setBackground(new java.awt.Color(84, 84, 246));
        BModificarP5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BModificarP5.setForeground(new java.awt.Color(255, 255, 255));
        BModificarP5.setText("Consultar Perfil");
        BModificarP5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(204, 249, 255));

        panelRound1.setBackground(new java.awt.Color(5, 179, 242));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GESTIÓN DE PERFIL");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel12)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound2.setBackground(new java.awt.Color(5, 179, 242));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextCI.setEditable(false);
        TextCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCIActionPerformed(evt);
            }
        });
        TextCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextCIKeyTyped(evt);
            }
        });
        panelRound2.add(TextCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 200, 30));

        TextCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCorreoActionPerformed(evt);
            }
        });
        TextCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextCorreoKeyTyped(evt);
            }
        });
        panelRound2.add(TextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 230, 30));

        TextDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDireccionActionPerformed(evt);
            }
        });
        TextDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextDireccionKeyTyped(evt);
            }
        });
        panelRound2.add(TextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 312, 232, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 64, 64));
        jLabel1.setText("Cédula");
        panelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 194, 20));

        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });
        panelRound2.add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 232, 30));

        TextClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextClaveActionPerformed(evt);
            }
        });
        panelRound2.add(TextClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 200, 30));

        TextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextNombreKeyTyped(evt);
            }
        });
        panelRound2.add(TextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 232, 30));

        TablaPerfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaPerfiles);

        panelRound2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 37, 410, 390));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(64, 64, 64));
        jLabel9.setText("Nombre completo");
        panelRound2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 194, 26));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(64, 64, 64));
        jLabel10.setText("Dirección corta");
        panelRound2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 274, 194, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(64, 64, 64));
        jLabel11.setText("Correo electrónico");
        panelRound2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 194, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(64, 64, 64));
        jLabel13.setText("Teléfono");
        panelRound2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 194, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(64, 64, 64));
        jLabel14.setText("Usuario");
        panelRound2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 194, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(64, 64, 64));
        jLabel15.setText("Clave");
        panelRound2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 194, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(64, 64, 64));
        jLabel16.setText("Cargo");
        panelRound2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 194, -1));

        panelRound4.setBackground(new java.awt.Color(204, 249, 255));
        panelRound4.setRoundBottomLeft(50);
        panelRound4.setRoundBottomRight(50);
        panelRound4.setRoundTopLeft(50);
        panelRound4.setRoundTopRight(50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos del usuario");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound2.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 11, -1, -1));

        Modificar.setText("Modificar Perfil");
        Modificar.setColorNormal(new java.awt.Color(153, 153, 153));
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        panelRound2.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        Eliminar.setBackground(new java.awt.Color(255, 153, 153));
        Eliminar.setText("Eliminar Perfil");
        Eliminar.setColorHover(new java.awt.Color(229, 0, 0));
        Eliminar.setColorNormal(new java.awt.Color(255, 153, 153));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        panelRound2.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

        Consultar.setText("Consultar Perfil");
        Consultar.setColorNormal(new java.awt.Color(153, 153, 153));
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        panelRound2.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));

        Cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Secretaria", "Odontologo" }));
        Cargo.setEnabled(false);
        Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoActionPerformed(evt);
            }
        });
        panelRound2.add(Cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 312, 200, 30));

        Error_Nombre.setEditable(false);
        Error_Nombre.setBackground(new java.awt.Color(0,0,0,1));
        Error_Nombre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Nombre.setBorder(null);
        panelRound2.add(Error_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, -1));

        Error_Cedula.setEditable(false);
        Error_Cedula.setBackground(new java.awt.Color(0,0,0,1));
        Error_Cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Cedula.setBorder(null);
        panelRound2.add(Error_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 240, 10));

        Error_Correo.setEditable(false);
        Error_Correo.setBackground(new java.awt.Color(0,0,0,1));
        Error_Correo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Correo.setBorder(null);
        panelRound2.add(Error_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 250, -1));

        CodNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "0212", "0412", "0414", "0424", "0416", "0426" }));
        CodNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodNumActionPerformed(evt);
            }
        });
        panelRound2.add(CodNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 30));

        TextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefonoActionPerformed(evt);
            }
        });
        TextTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextTelefonoKeyTyped(evt);
            }
        });
        panelRound2.add(TextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 110, 30));

        Error_Usuario.setEditable(false);
        Error_Usuario.setBackground(new java.awt.Color(0,0,0,1));
        Error_Usuario.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Usuario.setBorder(null);
        panelRound2.add(Error_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 260, -1));

        Error_Telefono.setEditable(false);
        Error_Telefono.setBackground(new java.awt.Color(0,0,0,1));
        Error_Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Telefono.setBorder(null);
        panelRound2.add(Error_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 180, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCIActionPerformed

    private void TextClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextClaveActionPerformed

    private void TextDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDireccionActionPerformed

    private void TextCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCorreoActionPerformed

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void TextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNombreKeyTyped
         int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)){
        
            JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales ni numeros","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
           
            evt.consume();
        }
    }//GEN-LAST:event_TextNombreKeyTyped

    private void TextCIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextCIKeyTyped
       
    }//GEN-LAST:event_TextCIKeyTyped

    private void TextDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDireccionKeyTyped
       int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32; 
        boolean numeros= (key >= 48 && key <= 57);
        if (!(minusculas || mayusculas || espacio || numeros)){
        
            JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
           
            evt.consume();
        }
    }//GEN-LAST:event_TextDireccionKeyTyped

  
    
    
    private void TextCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextCorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCorreoKeyTyped

    private void CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargoActionPerformed

    private void CodNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodNumActionPerformed

    private void TextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefonoActionPerformed

    private void TextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextTelefonoKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
        if (TextTelefono.getText().trim().length() >=7) {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA solo ingrese los otros 7 digitos","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_TextTelefonoKeyTyped

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (control.EliminarUsuario(Nom,Cedu)==true){
           //// dbemos hacer que al eliminar su perfil lo mande a la ventana iniciar sesion
        Limpiar();
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
       control.ConsultarPerfil();
    }//GEN-LAST:event_ConsultarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
      
        
        control.ModificarPerfil(Cedu, Nom);
      control.LlenarTablaPerfil();
    }//GEN-LAST:event_ModificarActionPerformed

    
    public void Limpiar(){
       TextNombre.setText("");
       TextCI.setText("");
       TextTelefono.setText("");
       TextUsuario.setText("");
       TextClave.setText("");
       TextCorreo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BModificarP5;
    private javax.swing.JComboBox<String> Cargo;
    private javax.swing.JComboBox<String> CodNum;
    private rsbuttom.RSButtonMetro Consultar;
    private rsbuttom.RSButtonMetro Eliminar;
    private javax.swing.JTextField Error_Cedula;
    private javax.swing.JTextField Error_Correo;
    private javax.swing.JTextField Error_Nombre;
    private javax.swing.JTextField Error_Telefono;
    private javax.swing.JTextField Error_Usuario;
    private rsbuttom.RSButtonMetro Modificar;
    private javax.swing.JPanel Principal;
    private javax.swing.JTable TablaPerfiles;
    private javax.swing.JTextField TextCI;
    private javax.swing.JTextField TextClave;
    private javax.swing.JTextField TextCorreo;
    private javax.swing.JTextField TextDireccion;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextTelefono;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Modelo.PanelRound panelRound1;
    private Modelo.PanelRound panelRound2;
    private Modelo.PanelRound panelRound4;
    // End of variables declaration//GEN-END:variables
}
