/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class modificar extends javax.swing.JPanel {
public static String Cedula_new = "";
    /**
     * Creates new form modificar
     */
    public modificar(String ci) {
        initComponents();
        String cu= ci;
        
     try{
         Connection cn = Conexion.conectarBD();
         PreparedStatement pst = cn.prepareStatement("select * from odontologos where Cedula = '" + ci + "'");

         ResultSet rs = pst.executeQuery();
         
         if(rs.next()){
             
             
             Nombre.setText(rs.getString("Nombre"));
             Cedula.setText(rs.getString("Cedula"));
             Direccion.setText(rs.getString("Direccion"));
             TextCargo.setText(rs.getString("Cargo"));
             TextEspe.setText(rs.getString("Especialidad"));
             TextTelefono.setText(rs.getString("Telefono"));
             
             Usuario.setText(rs.getString("Usuario"));
             Correo.setText(rs.getString("Correo"));
             Clave.setText(rs.getString("Clave"));
             TextObservaciones.setText(rs.getString("Observaciones"));
        }
         
        cn.close();
     }catch(Exception e){
         System.out.println("Error en cargar usuario " + e);
        // JOptionPane.showMessageDialog(null), "ESCRIBALE A ANDI");
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound3 = new Modelo.PanelRound();
        panelRound4 = new Modelo.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextTelefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ListTel = new javax.swing.JComboBox<>();
        TextObservaciones = new javax.swing.JTextField();
        TextCargo = new javax.swing.JTextField();
        TextEspe = new javax.swing.JTextField();
        BEliminar = new javax.swing.JButton();
        BModificar = new javax.swing.JButton();
        Error_Nombre = new javax.swing.JTextField();
        Error_Cedula = new javax.swing.JTextField();
        Error_Direccion = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Usuario = new javax.swing.JTextField();
        Clave = new javax.swing.JTextField();
        Error_Correo = new javax.swing.JTextField();
        Error_Usuario = new javax.swing.JTextField();

        panelRound3.setBackground(new java.awt.Color(145, 168, 213));
        panelRound3.setRoundBottomLeft(50);
        panelRound3.setRoundBottomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(50);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound4.setBackground(new java.awt.Color(204, 204, 204));
        panelRound4.setRoundBottomLeft(50);
        panelRound4.setRoundBottomRight(50);
        panelRound4.setRoundTopLeft(50);
        panelRound4.setRoundTopRight(50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos del Odontólogo");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound3.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 900, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Teléfono:");
        panelRound3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nombre Completo:");
        panelRound3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 73, -1, 38));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Dirección:");
        panelRound3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 85, 38));

        TextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefonoActionPerformed(evt);
            }
        });
        TextTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextTelefonoKeyTyped(evt);
            }
        });
        panelRound3.add(TextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, 31));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Cédula:");
        panelRound3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 85, 38));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Especialidad:");
        panelRound3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Cargo:");
        panelRound3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Correo electrónico:");
        panelRound3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Usuario:");
        panelRound3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Observaciones:");
        panelRound3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Contraseña:");
        panelRound3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        ListTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "0212", "0412", "0414", "0424", "0416", "0426" }));
        ListTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListTelActionPerformed(evt);
            }
        });
        panelRound3.add(ListTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, 30));
        panelRound3.add(TextObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 170, 30));
        panelRound3.add(TextCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 170, 30));

        TextEspe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEspeActionPerformed(evt);
            }
        });
        panelRound3.add(TextEspe, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 170, 30));

        BEliminar.setBackground(new java.awt.Color(102, 153, 255));
        BEliminar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BEliminar.setText("Eliminar");
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });
        panelRound3.add(BEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 170, 40));

        BModificar.setBackground(new java.awt.Color(102, 153, 255));
        BModificar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BModificar.setForeground(new java.awt.Color(255, 255, 255));
        BModificar.setText("Modificar");
        BModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificarActionPerformed(evt);
            }
        });
        panelRound3.add(BModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 160, 40));

        Error_Nombre.setEditable(false);
        Error_Nombre.setBackground(new java.awt.Color(0,0,0,1));
        Error_Nombre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Nombre.setForeground(new java.awt.Color(255, 0, 0));
        Error_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Nombre.setBorder(null);
        panelRound3.add(Error_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 240, 20));

        Error_Cedula.setEditable(false);
        Error_Cedula.setBackground(new java.awt.Color(0,0,0,1));
        Error_Cedula.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Cedula.setForeground(new java.awt.Color(255, 0, 0));
        Error_Cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Cedula.setBorder(null);
        Error_Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_CedulaActionPerformed(evt);
            }
        });
        panelRound3.add(Error_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 250, 20));

        Error_Direccion.setEditable(false);
        Error_Direccion.setBackground(new java.awt.Color(0,0,0,1));
        Error_Direccion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Direccion.setForeground(new java.awt.Color(255, 0, 0));
        Error_Direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Direccion.setBorder(null);
        Error_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_DireccionActionPerformed(evt);
            }
        });
        panelRound3.add(Error_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 260, 20));

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });
        panelRound3.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, 30));

        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });
        Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CedulaKeyTyped(evt);
            }
        });
        panelRound3.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 218, 30));

        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionKeyTyped(evt);
            }
        });
        panelRound3.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 230, 30));

        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CorreoKeyTyped(evt);
            }
        });
        panelRound3.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 250, 30));

        Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioKeyTyped(evt);
            }
        });
        panelRound3.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 190, 30));

        Clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ClaveKeyTyped(evt);
            }
        });
        panelRound3.add(Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 213, 30));

        Error_Correo.setEditable(false);
        Error_Correo.setBackground(new java.awt.Color(0,0,0,1));
        Error_Correo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Correo.setForeground(new java.awt.Color(255, 0, 0));
        Error_Correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Correo.setBorder(null);
        Error_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_CorreoActionPerformed(evt);
            }
        });
        panelRound3.add(Error_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 280, 20));

        Error_Usuario.setEditable(false);
        Error_Usuario.setBackground(new java.awt.Color(0,0,0,1));
        Error_Usuario.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Usuario.setForeground(new java.awt.Color(255, 0, 0));
        Error_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Usuario.setBorder(null);
        panelRound3.add(Error_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 260, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefonoActionPerformed

    private void TextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextTelefonoKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras (solo numeros)","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
        if (TextTelefono.getText().trim().length() >=7) {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA el telefono debe tener 7 digitos","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_TextTelefonoKeyTyped

    private void ListTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListTelActionPerformed

    private void TextEspeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEspeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEspeActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        
       String ci= Cedula.getText();
        try {
            Connection cn = Conexion.conectarBD();
            String sql = "DELETE FROM odontologos WHERE Cedula = '" + ci + "'"; // le indico a quien debe borra pasandole la cedula
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.executeUpdate();
            cn.close();
            JOptionPane.showMessageDialog(null,"¡El cliente fue eliminado con éxito!");
            
        } catch (Exception e) {
           System.err.println("Error al eliminar al usuario de la tabla." + e);
           JOptionPane.showMessageDialog(null, "Debe estara ctivo la base de datos, ¡Contacte al administrador!");}
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificarActionPerformed
      int permisos, estatus, validacion =0;
      String nombre, cargo, mail, telefono, ci, direccion, usuario, especialidad, clave, observaciones;
      
      cargo = TextCargo.getText().trim();
      mail = Correo.getText().trim();
      nombre = Nombre.getText().trim();
      ci = Cedula.getText().trim();
      direccion = Direccion.getText().trim();
      telefono = TextTelefono.getText().trim();
      usuario = Usuario.getText().trim();
      especialidad = TextEspe.getText().trim();
      clave = Clave.getText().trim();
      observaciones = TextObservaciones.getText().trim();
      
      if(mail.equals("")){
          Correo.setBackground(Color.red);
          validacion ++;
      }
      if(nombre.equals("")){
          Nombre.setBackground(Color.red);
          validacion ++;
      }
      if(ci.equals("")){
          Cedula.setBackground(Color.red);
          validacion ++;
      }
      if(direccion.equals("")){
          Direccion.setBackground(Color.red);
          validacion ++;
      }
      if(telefono.equals("")){
          TextTelefono.setBackground(Color.red);
          validacion ++;
      }
      if(usuario.equals("")){
          Usuario.setBackground(Color.red);
          validacion ++;
      }
      if(especialidad.equals("")){
          TextEspe.setBackground(Color.red);
          validacion ++;
      }
      if(clave.equals("")){
          Clave.setBackground(Color.red);
          validacion ++;
      }
      
      if(validacion==0){
       
          try {
                  Connection cn2 = Conexion.conectarBD();
                  String Ssql = "UPDATE odontologos SET Nombre= ?, Direccion= ?, Telefono= ?, Correo= ?, Usuario= ?, Clave= ?, Especialidad= ?, Observaciones= ? " + "WHERE Cedula = '" + ci + "'";
                  PreparedStatement prest = cn2.prepareStatement(Ssql);
                 
                  
                  prest.setString(1, nombre);
                    prest.setString(2, direccion);
                    prest.setString(3, telefono);
                    prest.setString(4, mail);
                    prest.setString(5, usuario);
                    prest.setString(6, clave);
                    prest.setString(7, especialidad);
                     prest.setString(8, observaciones);

                    prest.executeUpdate();
              
                cn2.close();
                JOptionPane.showMessageDialog(null, "Modificacion correcta");
            
              
          } catch (Exception e) {
              System.err.println("Error al Actualizar "+ e);
          }
    
          
          
          
      } else{
          JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
      }
    }//GEN-LAST:event_BModificarActionPerformed

    private void Error_CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_CedulaActionPerformed

    private void Error_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_DireccionActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed

    }//GEN-LAST:event_NombreActionPerformed

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)){

            Error_Nombre.setText("No se aceptan caracteres especiales ni numeros");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales ni numeros","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);

            evt.consume();
        }
    }//GEN-LAST:event_NombreKeyTyped

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Cedula.setText("No se aceptan caracteres especiales ni letras");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
        if (Cedula.getText().trim().length() > 7) {
            Error_Cedula.setText("La cedula debe tener 6-8 digitos");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA la cedula debe tener 6-8 digitos","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_CedulaKeyTyped

    private void DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;
        boolean numeros= (key >= 48 && key <= 57);
        if (!(minusculas || mayusculas || espacio || numeros)){

            Error_Direccion.setText("No se aceptan caracteres especiales.");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);

            evt.consume();
        }
    }//GEN-LAST:event_DireccionKeyTyped

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoKeyTyped

    private void UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioKeyTyped

    private void ClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClaveKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ClaveKeyTyped

    private void Error_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_CorreoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BModificar;
    private javax.swing.JTextField Cedula;
    private javax.swing.JTextField Clave;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Error_Cedula;
    private javax.swing.JTextField Error_Correo;
    private javax.swing.JTextField Error_Direccion;
    private javax.swing.JTextField Error_Nombre;
    private javax.swing.JTextField Error_Usuario;
    private javax.swing.JComboBox<String> ListTel;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField TextCargo;
    private javax.swing.JTextField TextEspe;
    private javax.swing.JTextField TextObservaciones;
    private javax.swing.JTextField TextTelefono;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private Modelo.PanelRound panelRound3;
    private Modelo.PanelRound panelRound4;
    // End of variables declaration//GEN-END:variables
}
