/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.Controller;
import Modelo.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class RegistrarOdontologo extends javax.swing.JPanel {

    Controller control;
    String CeduNom;
    public RegistrarOdontologo() {
        initComponents();
        control= new Controller(TextNombre,  TextCedula, TextDireccion,  TextCorreo,  TextTelefono,TextCargo,  TextUsuario,  TextClave, TextEspecialidad,  Error_Nombre,  Error_Cedula,  Error_Correo, Error_Telefono,  Error_Especialidad, ListTel,  Error_Usuario, TextObservaciones);

    }
public RegistrarOdontologo(String CeduNom) {
        String Cedu[]= CeduNom.split("-");
        this.CeduNom=Cedu[0];
        
        initComponents();
        control= new Controller(TextNombre,  TextCedula, TextDireccion,  TextCorreo,  TextTelefono,TextCargo,  TextUsuario,  TextClave, TextEspecialidad,  Error_Nombre,  Error_Cedula,  Error_Correo, Error_Telefono,  Error_Especialidad, ListTel,  Error_Usuario, TextObservaciones);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelRound2 = new Modelo.PanelRound();
        panelRound1 = new Modelo.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        panelRound3 = new Modelo.PanelRound();
        panelRound4 = new Modelo.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        TextDireccion = new javax.swing.JTextField();
        TextTelefono = new javax.swing.JTextField();
        TextCedula = new javax.swing.JTextField();
        TextNombre = new javax.swing.JTextField();
        TextEspecialidad = new javax.swing.JTextField();
        TextObservaciones = new javax.swing.JTextField();
        TextClave = new javax.swing.JTextField();
        TextCorreo = new javax.swing.JTextField();
        TextUsuario = new javax.swing.JTextField();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        Error_Correo = new javax.swing.JTextField();
        Error_Nombre = new javax.swing.JTextField();
        Error_Cedula = new javax.swing.JTextField();
        Error_Direccion = new javax.swing.JTextField();
        Error_Telefono = new javax.swing.JTextField();
        Error_Especialidad = new javax.swing.JTextField();
        ListTel = new javax.swing.JComboBox<>();
        Error_Usuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TextCargo = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 249, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1005, 649));

        panelRound2.setBackground(new java.awt.Color(204, 204, 204));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        panelRound1.setBackground(new java.awt.Color(5, 179, 242));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("REGISTRAR ODONTÓLOGO");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelRound3.setBackground(new java.awt.Color(5, 179, 242));
        panelRound3.setRoundBottomLeft(50);
        panelRound3.setRoundBottomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(50);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound4.setBackground(new java.awt.Color(204, 249, 255));
        panelRound4.setRoundBottomLeft(50);
        panelRound4.setRoundBottomRight(50);
        panelRound4.setRoundTopLeft(50);
        panelRound4.setRoundTopRight(50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos del Odontólogo");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound3.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 900, 50));

        TextDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDireccionActionPerformed(evt);
            }
        });
        TextDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextDireccionKeyTyped(evt);
            }
        });
        panelRound3.add(TextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 230, 31));

        TextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefonoActionPerformed(evt);
            }
        });
        TextTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextTelefonoKeyTyped(evt);
            }
        });
        panelRound3.add(TextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, 31));

        TextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCedulaActionPerformed(evt);
            }
        });
        TextCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextCedulaKeyTyped(evt);
            }
        });
        panelRound3.add(TextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 230, 31));

        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });
        TextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextNombreKeyTyped(evt);
            }
        });
        panelRound3.add(TextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 240, 31));

        TextEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEspecialidadActionPerformed(evt);
            }
        });
        TextEspecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextEspecialidadKeyTyped(evt);
            }
        });
        panelRound3.add(TextEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 240, 30));

        TextObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextObservacionesActionPerformed(evt);
            }
        });
        panelRound3.add(TextObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 526, 76));

        TextClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextClaveActionPerformed(evt);
            }
        });
        panelRound3.add(TextClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 230, 31));

        TextCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCorreoActionPerformed(evt);
            }
        });
        panelRound3.add(TextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 240, 31));

        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });
        panelRound3.add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 230, 31));

        rSButtonMetro2.setText("Agregar");
        rSButtonMetro2.setColorHover(new java.awt.Color(104, 255, 104));
        rSButtonMetro2.setColorNormal(new java.awt.Color(113, 226, 113));
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });
        panelRound3.add(rSButtonMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 202, 45));

        Error_Correo.setEditable(false);
        Error_Correo.setBackground(new java.awt.Color(0,0,0,1));
        Error_Correo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Correo.setForeground(new java.awt.Color(255, 0, 0));
        Error_Correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Correo.setBorder(null);
        panelRound3.add(Error_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 240, 20));

        Error_Nombre.setEditable(false);
        Error_Nombre.setBackground(new java.awt.Color(0,0,0,1));
        Error_Nombre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Nombre.setForeground(new java.awt.Color(255, 0, 0));
        Error_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Nombre.setBorder(null);
        panelRound3.add(Error_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 240, 20));

        Error_Cedula.setEditable(false);
        Error_Cedula.setBackground(new java.awt.Color(0,0,0,1));
        Error_Cedula.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Cedula.setForeground(new java.awt.Color(255, 0, 0));
        Error_Cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Cedula.setBorder(null);
        panelRound3.add(Error_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 137, 180, 30));

        Error_Direccion.setEditable(false);
        Error_Direccion.setBackground(new java.awt.Color(0,0,0,1));
        Error_Direccion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Direccion.setForeground(new java.awt.Color(255, 0, 0));
        Error_Direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Direccion.setBorder(null);
        panelRound3.add(Error_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 190, 20));

        Error_Telefono.setEditable(false);
        Error_Telefono.setBackground(new java.awt.Color(0,0,0,1));
        Error_Telefono.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Telefono.setForeground(new java.awt.Color(255, 0, 0));
        Error_Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Telefono.setBorder(null);
        panelRound3.add(Error_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 233, 240, 20));

        Error_Especialidad.setEditable(false);
        Error_Especialidad.setBackground(new java.awt.Color(0,0,0,1));
        Error_Especialidad.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Especialidad.setForeground(new java.awt.Color(255, 0, 0));
        Error_Especialidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Especialidad.setBorder(null);
        panelRound3.add(Error_Especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 210, 20));

        ListTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "0212", "0412", "0414", "0424", "0416", "0426" }));
        ListTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListTelActionPerformed(evt);
            }
        });
        panelRound3.add(ListTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, 30));

        Error_Usuario.setEditable(false);
        Error_Usuario.setBackground(new java.awt.Color(0,0,0,1));
        Error_Usuario.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Usuario.setForeground(new java.awt.Color(255, 0, 0));
        Error_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Usuario.setBorder(null);
        panelRound3.add(Error_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 220, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Cédula");
        panelRound3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Dirección");
        panelRound3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Nombre Completo");
        panelRound3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Teléfono");
        panelRound3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Odontólogo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        panelRound3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 250, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Teléfono");
        panelRound3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Observaciones");
        panelRound3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Cargo");
        panelRound3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Especialidad");
        panelRound3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Correo electrónico");
        panelRound3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Usuario");
        panelRound3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Contraseña");
        panelRound3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        TextCargo.setBackground(new java.awt.Color(5, 179, 242));
        TextCargo.setBorder(null);
        panelRound3.add(TextCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void TextDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDireccionActionPerformed

    private void TextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefonoActionPerformed

    private void TextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCedulaActionPerformed

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreActionPerformed

    private void TextEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEspecialidadActionPerformed

    private void TextObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextObservacionesActionPerformed

    private void TextClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextClaveActionPerformed

    private void TextCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCorreoActionPerformed

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        int tipo_cmb, validacion = 0;
        String nombre,telefono,cedula,direccion, correo,observaciones, usuario, clave, especialidad;
        
        nombre = TextNombre.getText().trim();
        cedula = TextCedula.getText().trim();
        telefono = TextTelefono.getText().trim();
        direccion = TextDireccion.getText().trim();
        correo = TextCorreo.getText().trim();
        usuario = TextUsuario.getText().trim();
        clave = TextClave.getText().trim();
        especialidad = TextEspecialidad.getText().trim();
        observaciones = TextObservaciones.getText().trim();
        //tipo_cmb = cmbx_cliente.getSelectedIndex()+1; //Se le suma uno para trabajar contando a partir de 1 y no de 0.
        
        if(nombre.equals("")){
            TextNombre.setBackground(Color.red);
            validacion ++;
        }
        
        if(telefono.equals("")){
            TextTelefono.setBackground(Color.red);
            validacion ++;
        }
        
        if(cedula.equals("")){
            TextCedula.setBackground(Color.red);
            validacion ++;
        }
        
        if(direccion.equals("")){
            TextDireccion.setBackground(Color.red);
            validacion ++;
        }
        
        if(correo.equals("")){
            TextCorreo.setBackground(Color.red);
            validacion ++;
        }
        
        if(usuario.equals("")){
            TextUsuario.setBackground(Color.red);
            validacion ++;
        }
        
         if(clave.equals("")){
            TextClave.setBackground(Color.red);
            validacion ++;
        }
        
        if(especialidad.equals("")){
            TextEspecialidad.setBackground(Color.red);
            validacion ++;
        }
        
        if(observaciones.equals("")){
            TextObservaciones.setBackground(Color.red);
            validacion ++;
        }
      
        try {
            Connection cn = Conexion.conectarBD();
            PreparedStatement pst = cn.prepareStatement("select Cedula from odontologos where Cedula = '"+cedula+"'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                TextCedula.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "El número de cédula ingresado ya existe en la base de datos.","Odontólogo existente", JOptionPane.ERROR_MESSAGE);
                cn.close();
            }else{
                
                cn.close();
                
                if(validacion == 0){
                    
                    try {
                        Connection cn2 = Conexion.conectarBD();
                        PreparedStatement pst2 = cn2.prepareStatement("insert into odontologos values (?,?,?,?,?,?,?,?,?,?,?,?)");
                        
                        pst2.setString(1, nombre);
                        pst2.setString(2, cedula);
                        pst2.setString(3, direccion);
                        pst2.setString(4, telefono);
                        pst2.setString(5, correo);
                        pst2.setString(6, "Odontologo");
                        pst2.setString(7, usuario);
                        pst2.setString(8, clave);
                        pst2.setString(9, "2023-05-16");
                        pst2.setString(10, especialidad);
                        pst2.setString(11, "null");
                        pst2.setString(12, observaciones);
                        
                        
                        pst2.executeUpdate();
                        cn2.close();
                        
                        
                        
                        
                        
                        JOptionPane.showMessageDialog(null, "Registro exitoso.");
                        
                        Limpiar();
                        
                        
                    } catch (SQLException e) {
                        System.err.println("Error en ingresar odontólogo."+e);
                        JOptionPane.showMessageDialog(null, "Error al ingresar odontólogo.");
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Se deben llenar todos los campos.");
                }
                
                
            }
            
        } catch (SQLException e) {
            System.err.println("Error en validar cédula del odontólogo."+e);
            JOptionPane.showMessageDialog(null, "Error en comparar cédula del odontólogo.");
        }
       
    
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void TextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNombreKeyTyped
         int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)){
        
            Error_Nombre.setText("No se aceptan caracteres especiales ni números");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales ni numeros","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
           
            evt.consume();
        }
    }//GEN-LAST:event_TextNombreKeyTyped

    private void TextCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextCedulaKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Cedula.setText("No se aceptan caracteres especiales ni letras");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras (solo numeros)","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
        if (TextCedula.getText().trim().length() >=8) {
            
            Error_Cedula.setText("La cédula debe tener 6-8 dígitos");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA la cedula debe tener 6-8 digitos","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_TextCedulaKeyTyped

    private void TextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextTelefonoKeyTyped
         int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Telefono.setText("No se aceptan caracteres especiales ni letras");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras (solo numeros)","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
        if (TextTelefono.getText().trim().length() >=7) {
            
            Error_Telefono.setText("Seleccione e ingrese los últimos 7 dígitos");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA el telefono debe tener 7 digitos","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_TextTelefonoKeyTyped

    private void TextEspecialidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextEspecialidadKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)){
        
            Error_Especialidad.setText("No se aceptan caracteres especiales ni números");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales ni numeros (solo letras)","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
           
            evt.consume();
        }
    }//GEN-LAST:event_TextEspecialidadKeyTyped

    private void TextDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDireccionKeyTyped
         int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32; 
        boolean numeros= (key >= 48 && key <= 57);
        if (!(minusculas || mayusculas || espacio || numeros)){
        
            Error_Direccion.setText("No se aceptan caracteres especiales.");
           // JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
           
            evt.consume();
        }
    }//GEN-LAST:event_TextDireccionKeyTyped

    private void ListTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListTelActionPerformed

    public void Limpiar(){
        TextNombre.setText("");
        TextCedula.setText("");
        TextTelefono.setText("");
        TextDireccion.setText("");
        TextUsuario.setText("");
        TextClave.setText("");
        TextObservaciones.setText("");
        TextCorreo.setText("");
        TextEspecialidad.setText("");
        Error_Nombre.setText("");
        Error_Cedula.setText("");
        Error_Correo.setText("");
        Error_Telefono.setText("");
        Error_Direccion.setText("");
        Error_Especialidad.setText("");
        Error_Usuario.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Error_Cedula;
    private javax.swing.JTextField Error_Correo;
    private javax.swing.JTextField Error_Direccion;
    private javax.swing.JTextField Error_Especialidad;
    private javax.swing.JTextField Error_Nombre;
    private javax.swing.JTextField Error_Telefono;
    private javax.swing.JTextField Error_Usuario;
    private javax.swing.JComboBox<String> ListTel;
    private javax.swing.JTextField TextCargo;
    private javax.swing.JTextField TextCedula;
    private javax.swing.JTextField TextClave;
    private javax.swing.JTextField TextCorreo;
    private javax.swing.JTextField TextDireccion;
    private javax.swing.JTextField TextEspecialidad;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextObservaciones;
    private javax.swing.JTextField TextTelefono;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private Modelo.PanelRound panelRound1;
    private Modelo.PanelRound panelRound2;
    private Modelo.PanelRound panelRound3;
    private Modelo.PanelRound panelRound4;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    // End of variables declaration//GEN-END:variables
}
