/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controller;
import Modelo.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex Altuve
 */
public class RegistrarPerfilN extends javax.swing.JFrame {
Controller control;

    /**
     * Creates new form RegistrarPerfilN
     */
    public RegistrarPerfilN() {
        initComponents();
        control= new Controller(Nombre,Cedula,Direccion,Telefono, Correo,Cargo, Usuario, Clave, Error_Nombre, Error_Direccion, Error_Correo, CodNum, Error_Usuario, Error_Telefono);
        control.iniciaVentana(this, "src/Imagenes/logoC.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelRound1 = new Modelo.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        panelRound2 = new Modelo.PanelRound();
        Nombre = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Usuario = new javax.swing.JTextField();
        Clave = new javax.swing.JTextField();
        Agregar = new rsbuttom.RSButtonMetro();
        Error_Nombre = new javax.swing.JTextField();
        Error_Direccion = new javax.swing.JTextField();
        Error_Correo = new javax.swing.JTextField();
        CodNum = new javax.swing.JComboBox<>();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        Error_Usuario = new javax.swing.JTextField();
        Error_Telefono = new javax.swing.JTextField();
        Error_Cedula = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Cargo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(151, 218, 252));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(5, 179, 242));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NUEVO PERFIL");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(248, 248, 248))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 862, -1));

        panelRound2.setBackground(new java.awt.Color(5, 179, 242));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });
        panelRound2.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 30));

        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });
        Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CedulaKeyTyped(evt);
            }
        });
        panelRound2.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 218, 30));

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });
        panelRound2.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 30));

        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CorreoKeyTyped(evt);
            }
        });
        panelRound2.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 230, 30));

        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionKeyTyped(evt);
            }
        });
        panelRound2.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 230, 30));

        Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioKeyTyped(evt);
            }
        });
        panelRound2.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 190, 30));

        Clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ClaveKeyTyped(evt);
            }
        });
        panelRound2.add(Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 213, 30));

        Agregar.setText("Registrarme");
        Agregar.setColorHover(new java.awt.Color(104, 255, 104));
        Agregar.setColorNormal(new java.awt.Color(113, 226, 113));
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        panelRound2.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 202, 45));

        Error_Nombre.setEditable(false);
        Error_Nombre.setBackground(new java.awt.Color(0,0,0,1));
        Error_Nombre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Nombre.setForeground(new java.awt.Color(255, 0, 0));
        Error_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Nombre.setBorder(null);
        panelRound2.add(Error_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 240, 20));

        Error_Direccion.setEditable(false);
        Error_Direccion.setBackground(new java.awt.Color(0,0,0,1));
        Error_Direccion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Direccion.setForeground(new java.awt.Color(255, 0, 0));
        Error_Direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Direccion.setBorder(null);
        Error_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_DireccionActionPerformed(evt);
            }
        });
        panelRound2.add(Error_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 260, 20));

        Error_Correo.setEditable(false);
        Error_Correo.setBackground(new java.awt.Color(0,0,0,1));
        Error_Correo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Correo.setForeground(new java.awt.Color(255, 0, 0));
        Error_Correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Correo.setBorder(null);
        Error_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_CorreoActionPerformed(evt);
            }
        });
        panelRound2.add(Error_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 330, 20));

        CodNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "0212", "0412", "0414", "0424", "0416", "0426" }));
        CodNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodNumActionPerformed(evt);
            }
        });
        panelRound2.add(CodNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, 30));

        rSButtonMetro1.setText("Regresar");
        rSButtonMetro1.setColorNormal(new java.awt.Color(153, 153, 255));
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        panelRound2.add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 120, 30));

        Error_Usuario.setEditable(false);
        Error_Usuario.setBackground(new java.awt.Color(0,0,0,1));
        Error_Usuario.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Usuario.setForeground(new java.awt.Color(255, 0, 0));
        Error_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Usuario.setBorder(null);
        panelRound2.add(Error_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 260, 20));

        Error_Telefono.setEditable(false);
        Error_Telefono.setBackground(new java.awt.Color(0,0,0,1));
        Error_Telefono.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Telefono.setForeground(new java.awt.Color(255, 0, 0));
        Error_Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Telefono.setBorder(null);
        Error_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_TelefonoActionPerformed(evt);
            }
        });
        panelRound2.add(Error_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 240, 20));

        Error_Cedula.setEditable(false);
        Error_Cedula.setBackground(new java.awt.Color(0,0,0,1));
        Error_Cedula.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Cedula.setForeground(new java.awt.Color(255, 0, 0));
        Error_Cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Cedula.setBorder(null);
        Error_Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_CedulaActionPerformed(evt);
            }
        });
        panelRound2.add(Error_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 250, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Secretaria");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 210, 30));

        Cargo.setBackground(new java.awt.Color(5, 179, 242));
        Cargo.setBorder(null);
        panelRound2.add(Cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 10, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setText("Clave");
        panelRound2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setText("Nombre Completo");
        panelRound2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setText("Cédula");
        panelRound2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("Dirección corta");
        panelRound2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setText("Teléfono");
        panelRound2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setText("Correo electrónico");
        panelRound2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setText("Cargo");
        panelRound2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel23.setText("Usuario");
        panelRound2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, 30));

        jPanel2.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, 860, 460));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -8, 880, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        //control.RegistrarPerfil();
          int tipo_cmb, validacion = 0;
        String nombre,telefono,cedula,correo, direccion,cargo = "Secretaria", usuario, clave;
        
        nombre = Nombre.getText().trim();
        cedula = Cedula.getText().trim();
        telefono = Telefono.getText().trim();
        correo = Correo.getText().trim();
        direccion = Direccion.getText().trim();
        usuario = Usuario.getText().trim();
        clave = Clave.getText().trim();
        
        //tipo_cmb = cmbx_cliente.getSelectedIndex()+1; //Se le suma uno para trabajar contando a partir de 1 y no de 0.
        
        if(nombre.equals("")){
            Nombre.setBackground(Color.red);
            validacion ++;
        }
        
        if(telefono.equals("")){
            Telefono.setBackground(Color.red);
            validacion ++;
        }
        
        if(cedula.equals("")){
            Cedula.setBackground(Color.red);
            validacion ++;
        }
        if(correo.equals("")){
            Correo.setBackground(Color.red);
            validacion ++;
        }
        
        if(direccion.equals("")){
            Direccion.setBackground(Color.red);
            validacion ++;
        }
        
        if(usuario.equals("")){
            Usuario.setBackground(Color.red);
            validacion ++;
        }
        if(clave.equals("")){
            Clave.setBackground(Color.red);
            validacion ++;
        }
      
      
        try {
            Connection cn = Conexion.conectarBD();
            PreparedStatement pst = cn.prepareStatement("select Cedula from secretarias where Cedula = '"+cedula+"'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                Cedula.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "El número de cédula ingresado ya existe en la base de datos.","Perfil existente", JOptionPane.ERROR_MESSAGE);
                cn.close();
            }else{
                
                cn.close();
                
                try {
                    Connection cn1 = Conexion.conectarBD();
                    PreparedStatement pst1 = cn1.prepareStatement("select Usuario from secretarias where Usuario = '"+usuario+"'");
                    ResultSet rs1 = pst1.executeQuery();
                    
                    if(rs1.next()){
                    Usuario.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "El usuario ingresado ya existe en la base de datos.","Nombre de usuario existente", JOptionPane.ERROR_MESSAGE);
                    cn1.close();
                    }else{
                        
                    cn1.close();
                    
                    if(validacion == 0){
                    
                    try {
                        Connection cn2 = Conexion.conectarBD();
                        PreparedStatement pst2 = cn2.prepareStatement("insert into secretarias values (?,?,?,?,?,?,?,?,?)");
                        
                        pst2.setString(1, nombre);
                        pst2.setString(2, cedula);
                        pst2.setString(3, direccion);
                        pst2.setString(4, telefono);
                        pst2.setString(5, correo);
                        pst2.setString(6, cargo);
                        pst2.setString(7, usuario);
                        pst2.setString(8, clave);
                        pst2.setString(9, "2023-05-18");
                       
                        
                        
                        pst2.executeUpdate();
                        cn2.close();
                        
                        
                        
                        
                        
                        JOptionPane.showMessageDialog(null, "Registro exitoso.");
                        
                        
                    } catch (SQLException e) {
                        System.err.println("Error en validar el usuario."+e);
                        JOptionPane.showMessageDialog(null, "Error al comparar la cédula del perfil.");
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Se deben llenar todos los campos.");
                }
                
                }
                } catch (Exception e) {
                    System.err.println("Error en ingresar perfil."+e);
                    JOptionPane.showMessageDialog(null, "Error al ingresar perfil.");
                }
                
                
                
                
                
            }
            
        } catch (SQLException e) {
            System.err.println("Error en validar cédula del perfil."+e);
            JOptionPane.showMessageDialog(null, "Error en comparar cédula del perfil.");
        }
       
        Login logueo = new Login();
        logueo.setVisible(true);
        this.dispose();   
    }//GEN-LAST:event_AgregarActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
       
    }//GEN-LAST:event_NombreActionPerformed

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)){
            
            Error_Nombre.setText("No se aceptan caracteres especiales ni números");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales ni numeros","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
           
            evt.consume();
        }
    }//GEN-LAST:event_NombreKeyTyped

    private void CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Cedula.setText("No se aceptan caracteres especiales ni letras");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
        if (Cedula.getText().trim().length() > 7) {
            Error_Cedula.setText("La cédula debe tener 6-8 dígitos");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA la cedula debe tener 6-8 digitos","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_CedulaKeyTyped

    private void DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32; 
        boolean numeros= (key >= 48 && key <= 57);
        if (!(minusculas || mayusculas || espacio || numeros)){
        
            Error_Direccion.setText("No se aceptan caracteres especiales.");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
           
            evt.consume();
        }
    }//GEN-LAST:event_DireccionKeyTyped

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
       int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Telefono.setText("No se aceptan caracteres especiales ni letras");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
        if (Telefono.getText().trim().length() >=7) {
            Error_Telefono.setText("Seleccione e ingrese los últimos 7 dígitos");
            //JOptionPane.showMessageDialog(null, "ADVERTENCIA solo ingrese los otros 7 digitos","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_TelefonoKeyTyped

    private void CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoKeyTyped

    private void UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioKeyTyped

    private void ClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClaveKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ClaveKeyTyped

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void CodNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodNumActionPerformed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        Login destino = new Login();
        control.activaVentana(destino, this);
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void Error_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_DireccionActionPerformed

    private void Error_CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_CedulaActionPerformed

    private void Error_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_TelefonoActionPerformed

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void Error_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_CorreoActionPerformed

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPerfilN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPerfilN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPerfilN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPerfilN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPerfilN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro Agregar;
    private javax.swing.JTextField Cargo;
    private javax.swing.JTextField Cedula;
    private javax.swing.JTextField Clave;
    private javax.swing.JComboBox<String> CodNum;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Error_Cedula;
    private javax.swing.JTextField Error_Correo;
    private javax.swing.JTextField Error_Direccion;
    private javax.swing.JTextField Error_Nombre;
    private javax.swing.JTextField Error_Telefono;
    private javax.swing.JTextField Error_Usuario;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Telefono;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private Modelo.PanelRound panelRound1;
    private Modelo.PanelRound panelRound2;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    // End of variables declaration//GEN-END:variables
}
